### ISSUE TITLE
Soporte para composer PSR-4

### ISSUE THREAD

**Issue by Faryshta** [quiubas/quiubas-php#1]
Hola, la api actual no funciona adecuadamente con composer ya que no cumple el estandard PSR-4 ni el PSR-0 

http://www.php-fig.org/psr/psr-0/

http://www.php-fig.org/psr/psr-4/

esto causa que cada vez que hay un error en cualquier archivo aún fuera de quiubas, automaticamente me salta un mensaje que sobre la linea https://github.com/quiubas/quiubas-php/blob/master/quiubas.php#L11

y detiene mi proceso por completo.

El soporte implica re-estructurar la forma en que se guardan los archivos y re escribir el autoloader para que sea opcional, por defecto usar composer.

Saludos

**Comment by neverabe** [comment]
@zo0r Estimado Jorge, tenemos atorada la operación de testers por este issue que comenta @Faryshta, por favor apoyanos a resolver y de ser posible explicanos como podemos resolverlo.

En todo nuestro código para debugear nos arroja errores de quiubas, lo cual genera muchas complicaciones.

Espero tus comentarios @zo0r

**Comment by zo0r** [comment]
@neverabe @Faryshta he realizado un nuevo [release](https://github.com/quiubas/quiubas-php/releases/tag/1.0.4) que soluciona el posible error que les esta ocurriendo. Solo descarguen nuevamente el **zipball** o instalen via **composer**.

Quedo pendiente de su confirmación si se les soluciono.

De no ser así les agradezco un **dump** exacto del error.

Saludos.

**Comment by Faryshta** [comment]
@zo0r gracias por la respuesta pero eso no es el soporte para PSR4 que esperabamos.

composer tiene una forma automatica para hacer el autoloading cambiando la linea https://github.com/quiubas/quiubas-php/blob/master/composer.json#L27 por

```json
    "autoload": {
        "psr-4": {
            "Quiubas\\": "quiubas/"
        }
    },
```
y luego cambiar los archivos para que sigan el estandard http://www.php-fig.org/psr/psr-4/

**Comment by zo0r** [comment]
@Faryshta podrías enviar un *PR*?

**Comment by Faryshta** [comment]
ok lo escribo mañana

**Comment by neverabe** [comment]
@zo0r con este fix, hice algunas pruebas y ya pude debugear sin que me aparezcan errores de quiubas, agradezco tu pronta respuesta, por otro lado esperamos el PR de @Faryshta para que tenga soporte para PSR4.

**Comment by asfo** [comment]
Cierro. Implementado soporte PSR-4 en 2.0.
